package com.newgrounds.components;

extern class APIConnector extends flash.display.MovieClip, implements Dynamic {
	var __setPropDict : flash.utils.Dictionary;
	var _redirect : Bool;
	var ad : FlashAd;
	var adType : String;
	var apiId : String;
	var className : String;
	var connectorType : String;
	var debugMode : String;
	var encryptionKey : String;
	var loader : Preloader;
	var movieVersion : String;
	var redirectOnHostBlocked : Bool;
	var redirectOnNewVersion : Bool;
	function new() : Void;
	function __setProp_ad_APIConnector_AD_0() : Dynamic;
	function _apiConnect() : Void;
	function _onConnected(p1 : com.newgrounds.APIEvent) : Void;
	function _onLoaded() : Void;
	function forceAlwaysOnTop() : Void;
	function frame1() : Dynamic;
	function frame10() : Dynamic;
	function frame11() : Dynamic;
	function frame12() : Dynamic;
	function frame13() : Dynamic;
	function frame14() : Dynamic;
	function frame15() : Dynamic;
	function frame16() : Dynamic;
	function frame17() : Dynamic;
	function frame18() : Dynamic;
	function frame19() : Dynamic;
	function frame2() : Dynamic;
	function frame20() : Dynamic;
	function frame21() : Dynamic;
	function frame3() : Dynamic;
	function frame4() : Dynamic;
	function frame5() : Dynamic;
	function frame6() : Dynamic;
	function frame7() : Dynamic;
	function frame8() : Dynamic;
	function frame9() : Dynamic;
}
