package com.newgrounds.components;

extern class SaveBrowser extends flash.display.MovieClip, implements Dynamic {
	var _currentQuery : com.newgrounds.SaveQuery;
	var _customQuery : com.newgrounds.SaveQuery;
	var _initialized : Bool;
	var _loading : Bool;
	var _numIcons : UInt;
	var _page : UInt;
	var _saveGroup : com.newgrounds.SaveGroup;
	var _sortLabel : String;
	var customSortField : String;
	var file : com.newgrounds.SaveFile;
	var i : UInt;
	var iconClip : flash.display.MovieClip;
	var iconList : flash.display.MovieClip;
	var infoBox : flash.display.MovieClip;
	var items : Array<Dynamic>;
	var listBox : flash.display.MovieClip;
	var nextButton : flash.display.SimpleButton;
	var orderButton : flash.display.MovieClip;
	var orderText : flash.text.TextField;
	var pageText : flash.text.TextField;
	var prevButton : flash.display.SimpleButton;
	var reloadButton : flash.display.SimpleButton;
	var saveGroupName : String;
	var sortDescending : Bool;
	var sortField : String;
	var title : String;
	var titleText : flash.text.TextField;
	function new() : Void;
	function _clearFiles() : Void;
	function _onFileClick(p1 : flash.events.MouseEvent) : Void;
	function _onFileLoaded(p1 : com.newgrounds.APIEvent) : Void;
	function _onFileOut(p1 : flash.events.MouseEvent) : Void;
	function _onFileOver(p1 : flash.events.MouseEvent) : Void;
	function _onListChange(p1 : Dynamic) : Void;
	function _onOrderClick(p1 : flash.events.MouseEvent) : Void;
	function _onPageClick(p1 : flash.events.MouseEvent) : Void;
	function _onQueryComplete(p1 : com.newgrounds.APIEvent) : Void;
	function _onReloadClick(p1 : flash.events.MouseEvent) : Void;
	function frame1() : Dynamic;
	function frame10() : Dynamic;
	function frame2() : Dynamic;
	function frame20() : Dynamic;
	function frame28() : Dynamic;
	function frame29() : Dynamic;
	function frame37() : Dynamic;
	function loadFiles() : Void;
	function setQuery(p1 : com.newgrounds.SaveQuery) : Void;
}
